"""Does the bolt list match the geometry, and does the order sheet match the
bolt list?  See cad/fasteners.py.

Two ways the fasteners were a paper claim nothing checked against reality, both
found 2026-08-06:

  - 16 heat-set inserts were on the BOM with no 3.5 mm bore in any part to seat
    them. bom() counts intent; nothing counted bores.
  - docs/order-sheet.md's fastener table claimed to be generated by cad.fasteners
    and had drifted from it - 40 deleted case screws, missing the horn and clamp
    bolts.
"""

import re
from pathlib import Path

from cad.fasteners import inserts_seated, fastener_order

ORDER_SHEET = Path(__file__).resolve().parent.parent / "docs" / "order-sheet.md"


def test_every_scheduled_insert_has_a_bore():
    """Ordered inserts must have somewhere to seat. PINNED as a known shortfall,
    not asserted away: the 3.5 mm bores are not in the geometry yet - the chassis
    cuts a 2.7 mm clearance hole and the yoke has nothing, so the part-to-part
    joints have no thread. This is the tests/test_floating.py pattern, which held
    the four floating servos as a list until they were seated: a static red rots
    into furniture (docs/road-to-order.md #3), a pinned shortfall screams the
    moment it CHANGES.

    When the bores go into the chassis and yoke, this fails with a smaller
    shortfall - shrink KNOWN, and flip to `== []` when it reaches empty.

    2026-08-06: every scheduled insert has a bore. The chassis closed (4 Pi
    standoff bores cut, the 8 "side plates -> top" inserts dropped as a joint a
    one-piece chassis does not have), and the yoke closed (2 set-screw bores in
    the pitch boss retain the ankle-pitch shaft). This now asserts EMPTY, which
    is the whole point of the pin: it went from a documented shortfall to zero.
    """
    assert inserts_seated(verbose=False) == []


def _order_sheet_fasteners():
    """{normalised part: qty} parsed out of the order sheet's fastener table.

    Keys are normalised to how cad.fasteners names them - 'M3 x 8', 'M2.5 insert',
    'M3 nut' - so a row's prose ('socket cap', '(rod-2 clamp)') does not matter.
    """
    text = ORDER_SHEET.read_text()
    # The fastener section: from its heading to the next one.
    sec = text.split("## 3. Fasteners", 1)[1].split("\n## ", 1)[0]
    out = {}
    for line in sec.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        label, qty = cells[0], cells[-1]
        msize = re.match(r"(M\d+(?:\.\d+)?)", label)
        if not msize or not qty.isdigit():
            continue                       # header, separator, prose row
        size = msize.group(1)
        if "insert" in label:
            key = f"{size} insert"
        elif "nut" in label:
            key = f"{size} nut"
        else:
            length = re.search(r"x\s*(\d+)", label)
            if not length:
                continue
            key = f"{size} x {length.group(1)}"
        out[key] = out.get(key, 0) + int(qty)
    return out


def test_order_sheet_fasteners_match_the_schedule():
    """The order sheet's fastener rows must equal cad.fasteners.fastener_order().
    It is the file money is spent from and it claimed to be generated by the
    command while having drifted from it; this makes the claim enforceable.
    """
    parsed = _order_sheet_fasteners()
    assert len(parsed) >= 6, f"parsed too few fastener rows: {parsed}"
    assert parsed == fastener_order()
